### PR TITLE
Document full date range syntax to `--date` flag, and clarify that it's all UTC.

### PR DESCRIPTION
**Pull request by Wilm0r**
Specifying an exact date range seems the most useful to many so it was nice to see that it's already supported. :)

### CODE REVIEW

**Comment by simulot** [comment]
Living on UTC+1 or UTC+2, this issue hasn't hurt me!
Thanks for the PR.

Apparently, some users are living on the other side of the globe. Wouldn't local time make more sense?

**Comment by Wilm0r** [comment]
> Living on UTC+1 or UTC+2, this issue hasn't hurt me!

Hah yes, same here for most of my life. I've started finding the more interesting issues now that I live in another continent for a while.

Local time would definitely be better yes, but there's a catch still. Imagine me being in Boston now and wanting to import all pictures from a given day that I spent back in The Netherlands. If the `--date` is blindly interpreted as local-to-where-I-am-right-now it won't do that properly. :(

So you'd probably have to store what's passed to the flag in raw form instead of as a processed computer-friendly timestamp, and really do a year-month-day comparison on every picture I think?

**Comment by simulot** [comment]
> Local time would definitely be better yes, but there's a catch still. Imagine me being in Boston now and wanting to import all pictures from a given day that I spent back in The Netherlands. If the `--date` is blindly interpreted as local-to-where-I-am-right-now it won't do that properly. :(
> 
> So you'd probably have to store what's passed to the flag in raw form instead of as a processed computer-friendly timestamp, and really do a year-month-day comparison on every picture I think?


There isn't a good solution. 
Some camera stores the date taken without time zone, some does.
Sometimes the file name is a timestamp, either in local time (Samsung) or UTC (pixel)...

What if you took photos with your phone during a trip, and the phone stores dates in local time for the visited country, but without giving the time zone... 

Back at home, how to select them by date, precisely?

**Comment by simulot** [comment]
I have taken into account your concern in the next branch.

**Pull request closed without merging**
