### PR TITLE
Fix typo on readme

### PR DESCRIPTION
**Pull request by Alkanov**

### CODE REVIEW

**Comment by Alkanov** [comment]
I dont think -log-file is working atm for some reason

**Comment by simulot** [comment]
-log-file works, I'm using it all the time.

**Comment by Alkanov** [comment]
In my case this is not working:

```
./immich-go -server=http://10.10.0.10:2283 -key=<removed> upload -create-album-folder=true -create-stacks=false -log-file=logfile pictures-after-google/
immich-go  0.9.6, commit 1782249564abb77f01780282ca4d8ddaf7ef6f69, built at 2023-12-30T08:30:25Z

Server status: OK
flag provided but not defined: -log-file
Usage of upload:
  -album string
        All assets will be added to this album.
  -create-album-folder
         folder import only: Create albums for assets based on the parent folder
  -create-albums
         google-photos only: Create albums like there were in the source (default: TRUE)
  -create-stacks
        Stack jpg/raw or bursts  (default TRUE)
  -date value
        Date of capture range.
  -discard-archived
         google-photos only: Do not import archived photos (default FALSE)
  -dry-run
        display actions but don't touch source or destination
  -exclude-types value
        list of excluded extensions separated by a comma
  -force-sidecar
        Upload the photo and a sidecar file with known information like date and GPS coordinates. With google-photos, information comes from the metadata files. (DEFAULT false)
  -from-album string
         google-photos only: Import only from this album
  -google-photos
        Import GooglePhotos takeout zip files
  -keep-partner
         google-photos only: Import also partner's items (default: TRUE)
  -keep-untitled-albums
         google-photos only: Keep Untitled albums and imports their contain (default: FALSE)
  -partner-album string
         google-photos only: Assets from partner will be added to this album. (ImportIntoAlbum, must already exist)
  -select-types value
        list of selected extensions separated by a comma
  -stack-burst
        Control the stacking bursts (default TRUE)
  -stack-jpg-raw
        Control the stacking of jpg/raw photos (default TRUE)
  -use-album-folder-as-name
         google-photos only: Use folder name and ignore albums' title (default:FALSE)
```

**Comment by Alkanov** [comment]
ah I see, -log-file has to be specified before the upload

**Comment by simulot** [comment]
Correct

**Pull request merged**
