### PR TITLE
Feature/tags

### LINKED ISSUE #484: Feature request: Add tag to uploaded files
Hi,

Now that tags are fully supported in immich, would it be possible to apply one or multiple tags when uploading pictures ?
I like to add a tag "to-review_UPLOAD-DATE" to my pictures so that I know which one I have to sort and review.

### PR DESCRIPTION
**Pull request by benjamonnguyen**
# Description
- Resolves #484
- Implement `UpsertTags`, `TagAssets`, `BulkTagAssets`, and `SendJobCommand` immich endpoints.
image

# Verification
test command: `immich-go upload -tags="test" -tag-with-session -tag-with-path ~/test`
immich-go-tags

### CODE REVIEW

**Comment by benjamonnguyen** [comment]
@tobiasgraeber updated the readme!

**Comment by benjamonnguyen** [comment]
Let's actually hold off on merging this.

I'm seeing an issue where sometimes assets aren't being tagged.

Opened an issue here: https://github.com/immich-app/immich/issues/13633

**Comment by simulot** [comment]
I'm wondering if it possible to leverage the tagging system to track immich-go uploads, and implement a kind of UNDO.

**Comment by benjamonnguyen** [comment]
@simulot implemented tag-session flag:
image

For now I've had to add a 5 second sleep. It looks like there's a race condition where the assets are being moved out of the upload directory into the library directory resulting in a stale path from the tagAssets request is made.

Waiting on a response from the immich team.

**Comment by simulot** [comment]
> @simulot implemented tag-session flag: image
> 

Nice! 
The session tag could be hierarchical has well. All upload would be under one master tag like  "immich-go/session_2006-01-02_15-04-05"

> For now I've had to add a 5 second sleep. It looks like there's a race condition where the assets are being moved out of the upload directory into the library directory resulting in a stale path from the tagAssets request is made.
> 
> Waiting on a response from the immich team.

Let's see how the discussion goes.

**Comment by simulot** [comment]
Thinking loud: 
Imagine your personal collection of assets is sorted patiently by years, topic and so one...
2009 / Petrified forest 
2009 / Grand canyon 
2009 / Cousins meeting
...

Using the path as tags makes sense, isn't it?

**Comment by benjamonnguyen** [comment]
> Using the path as tags makes sense, isn't it?

Silly of me to not think of this considering it's what motivated this PR in the first place. My wife has her folder structure like
|--Holidays
   |-- New Years
   |-- Halloween
   |-- Thanksgiving

and simply providing a flag `-tag-by-path` would be ideal.

Running list of possible flags...
-tag-by-path
-tag-with-session
-tags

**Comment by benjamonnguyen** [comment]
@simulot Got a workaround from an immich maintainer (https://github.com/immich-app/immich/discussions/13637#discussioncomment-11017586)

If things look ok to you, I think it's mergeable

**Comment by agittins** [comment]
How about a `-tag-by-path-separators` to further split the path component by a given set of chars?

My existing archive has folders named `2024/2024-02-05-event-name-or-such`, and I have subfolders named `out` for results of processing.

If that's a bit esoteric it's no problem for me, as I'll just use a bash script to call immich-go for each folder separately, building the tags list for each folder as it goes.

But either way, I'm keen to see this merged! :-)

**Comment by benjamonnguyen** [comment]
@agittins I think the 3 current flags covers our bases and a bash script leveraging them would be a cleaner

**Comment by benjamonnguyen** [comment]
@simulot after using it to upload and tag a few of my wife's albums, I think it'll be a cleaner CLI to break it out into its own `tag` command and treat it as a two step process. Upload then tag. Am also planning to implement `-remove-tags`

**Comment by simulot** [comment]
This could be one of the maintenance tools that we can propose through immich-go

fyi: I'm still on the code reorganization

**Comment by simulot** [comment]
The immich-go next version is more mature now.
Could you envisage to port the tag functionality in the `next` branch?
Feel free to discuss this

**Comment by simulot** [comment]
Don't rush on it... I'm still shaking the code

**Comment by benjamonnguyen** [comment]
If you don't mind, do you have a summary of the direction your taking with this next branch?

**Comment by benjamonnguyen** [comment]
I'll move the changes onto the next branch but you can look at my latest commits if you want to see the new tag command's options and implementation.

**Comment by simulot** [comment]
I'm ready to merge your PR. 
The next branch is so different now, than I don't know where to start while keep you credited for the feature.

**Comment by benjamonnguyen** [comment]
Are you going to merge next into main branch?

**Comment by simulot** [comment]
Can we chat on discord?

**Comment by benjamonnguyen** [comment]
Sure can you link me to the channel?

**Comment by simulot** [comment]
I'm reviewing your PR in details. 

1/ I'm sorry for having shacked all the source while you have worked on  it. 
2/ I would like to include the tag functionality in the upload command. Then it will be available for any source of photos
3/ I'm think to group immich editing functions like tag maintenance, raw/jpeg cleaning, stack bursts....


My channel is @simulot, Paris time zone.

**Comment by benjamonnguyen** [comment]
Linking to #522

**Pull request closed without merging**
