### PR TITLE
Add CI with Linting and Testing

### PR DESCRIPTION
**Pull request by rodneyosodo**
- **New Features**
	- Introduced Dependabot configuration for automated dependency updates.
	- Set up a CI pipeline for continuous integration, including linting, building, and testing.
- **Enhancements**
	- Improved efficiency in asset management and code readability across various modules.
	- Optimized error handling in Docker helper functions and added clarity in command-line tools.
	- Enhanced logic for date range handling and metadata extraction, improving reliability and user experience.
- **Bug Fixes**
	- Addressed issues with unnecessary code lines and spacing, enhancing the overall code quality.
	- Fixed inconsistencies in parameter naming and logic flow, ensuring better maintainability.
	
Signed-off-by: Rodney Osodo <28790446+rodneyosodo@users.noreply.github.com>

### CODE REVIEW

**Comment by simulot** [comment]
Thanks for this PR. 
I'm reading documentions on CI. This is new for me

**Review by simulot — COMMENTED** [review]
Is it a way to create a release with the binaries?

**Comment by rodneyosodo** [comment]
I thought goreleaser does this by default. This is something similar to how you have attached the binaries to the latest release: https://github.com/simulot/immich-go/releases/tag/0.10.0 . On the CI, I just added the compile check, i.e. everything pushed to the main needs to compile for the different platforms.

**Comment by simulot** [comment]
Yes, goreleaser does that.  I'm wondering if it's possible delegate the binaries build to the CI.

Fine, let's merge the PR.
Thanks for your work

**Comment by rodneyosodo** [comment]
You meant something like this https://github.com/goreleaser/goreleaser/blob/main/.github/workflows/release.yml

When you push, let's say tag v0.11.0, it should kick off ci and generate a release either as a draft before you approve to an actual release

**Pull request merged**
